site_name: DigiDocService Specification
theme_dir: 'theme/cinder/cinder' 
extra_css:
  - css/override.css
extra_javascript:
  - js/custom.js
extra:
  last_updated: '01.10.2020'
  service_version: '3.11.7'
  document_version: '3.11.7'
pages:
  - Overview: index.md

