site_name: DigiDocService Specification
theme_dir: 'theme/cinder/cinder' 
extra_css:
  - css/override.css
extra_javascript:
  - js/custom.js
markdown_extensions:
  - grid_tables
extra:
  last_updated: '23.10.2017'
  service_version: '3.11.1'
  document_version: '3.11.1'
pages:
  - Overview: index.md      
  - API Docs: api/api_docs.md

